
curl -H "Accept: application/json" http://my-client-with-secret:secret@localhost:8080/oauth/token -d grant_type=client_credentials

###

curl -H "Authorization: Bearer 22f76f55-622d-4bc9-9b4b-0e2175db85cf" http://localhost:8080/hello

###

POST http://my-client-with-secret:secret@localhost:8080/oauth/token?grant_type=client_credentials HTTP/1.1
Accept: application/json

grant_type=client_credentials

###

GET http://localhost:8080/hello HTTP/1.1
Authorization: Bearer 0fbc947e-67b8-47ae-9282-77ffafaf1799
