spring:
  application:
    name: fibonacci-web
server:
  port: 8081
  # use a different path for the client (otherwise cookies are shared)
  context_path: /fibonacci-web
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
